version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: ".github/docker"
    schedule:
      interval: "daily"
    groups:
      docker:
        applies-to: version-updates
        patterns:
          - "*hatchet-engine*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
