name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Compose
        run: docker compose up -d

      - name: Wait for Hatchet
        run: sleep 10

      - name: Test
        run: |
          set -eux
          export HATCHET_CLIENT_TOKEN="$(docker exec hatchet-go-quickstart-hatchet-engine-1 "/bin/bash" -c "cat /hatchet/config/token.txt")"
          go test ./... -v -failfast

      - name: Teardown
        run: docker compose down

      - name: Logs
        if: always()
        run: docker compose logs
