name: test
on: pull_request
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Compose
        run: docker compose up -d

      - name: Test
        run: go test ./... -v -failfast

      - name: Teardown
        run: docker compose down
